version: '2'
services:
  nginx:
    build:
      context: ./manifest
      dockerfile: nginx.dockerfile
    depends_on:
    - app
    restart: always
    volumes:
    - ./html:/var/www/html
  app:
    build:
      context: ./manifest
      dockerfile: app.dockerfile
    env_file: .env
    environment:
    - ENV_MODE=prod
    restart: always
    volumes:
    - ./html:/var/www/html